### PR TITLE
Redid the code using other modules, and removed the need for ahk

### PR DESCRIPTION
**Pull request by Meyr991**
While I was finishing up, I saw that you've just updated the code lol
But I'll create this PR anyways, so that you can compare both and see which one fits best

All images are saved to the "images" folder, and logs are saved to the "logs" folder

Hopefully this will help :)

### CODE REVIEW

**Comment by Meyr991** [comment]
I basically replaced all the code, I don't know why it's conflicting 🙃

**Comment by fruitTheory** [comment]
Just updated everything ;_; , check it out -- I'll check yours out in a moment

**Comment by fruitTheory** [comment]
Maybe could do a merge branch to have both (not sure how that works) or just combine best of both.. idk but have to head out soon, got work in morning. Going to check your pull!

**Comment by Meyr991** [comment]
The way you checked if the window was selected or not was really smart, I'll update my code to include something similar !!

**Comment by Meyr991** [comment]
> Maybe could do a merge branch to have both (not sure how that works) or just combine best of both.. idk but have to head out soon, got work in morning. Going to check your pull!

Combining both would be a good idea

**Comment by Meyr991** [comment]
Added similar functionality to PR, and the new code keeps running even when the user changes window, it will go back to edge automatically and finish its job

**Review by fruitTheory — COMMENTED** [review]
Did a stress test for both main and fork

**Working well:**
-More automatic/autoactivate 
-Images folder
-Faster/better timing
-The way debug text is sctructured and time debug is smarter

One major bonus on forked is it still saves images when main was returning 403 on links like https://cdna.artstation.com/p/assets/images/images/062/076/268/large/idea-xu-1.jpg?1682318845
Believe main was having trouble with ?123 extension


**Issues/differences:**
-win32gui==221.6 doesnt need be in requirements breaks pip install some reason
-Returns png instead of native extension -- already self noted
-Still saves image for tab even if its just a website without extension 
-If it returns tab with empty url, ends script and doesnt save any images of other tabs
**returns:** requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

Then one that idk if there's a workaround but only runs if one instance of Edge is open, so have to close any others

**Overall:**
I think both have pluses and drawbacks, like push and pull .. Fork is faster, organized, and more automatic -- mains more clunky but more durable it seems. So idk, let me know what you think 
___

**Comment by Meyr991** [comment]
Very much agreed, fork is faster, and it's great at making it automatic, but introduced some errors not seen on main, I'll try to work on those, because some of them are kind of annoying to come by, like the one where it saves an image even if it's just a website, when those are fixed, hopefully there will not be any more of these annoying errors that break the program's functionality, and we're able to merge it to main, will mark pr as draft for now, I'll open it again when those errors are fixed, and we can compare both then

"Then one that idk if there's a workaround but only runs if one instance of Edge is open, so have to close any others"
About this, I can't think of a solution for it right now, maybe we could loop over all open windows of MS Edge and run the program, but idk
If you feel that's an issue that NEEDS to be solved, I can look into it, let me know what you think

**Comment by fruitTheory** [comment]
Eh, I think it's okay, if you end up updating ill merge it into main. Can always build on top like clay; I don't think there's a need to be a certain type of way. Thanks again for all the help :):)

**Comment by Meyr991** [comment]
Okay, I'm not that active on weekdays as I'm focused on other things normally, but I'll work on it some time
I'll try to keep up with your new additions as well
I'm happy to help man :)

**Comment by fruitTheory** [comment]
Yeah same here, can't do much coding on weekdays only before/after work, else that's all I'd be doing xD. And okay sounds good 👍

**Comment by fruitTheory** [comment]
@Meyr991 hey just wanted to let you know I used some of your code from pull in main, not everything like debug stuff because wanted to get permission first. But definitely used the 'xx has more tabs open' idea because that was actually genius lol. Think I can manually add you as a contributor if you wanted for credit, juust let me know.

**Comment by Meyr991** [comment]
Okay, not really a problem not being a contributor, I'll try to fix the problems with my code this weekend, so we can merge it !!

**Comment by Meyr991** [comment]
If you need a faster answer from me for something related to my code, dm me on discord

**Comment by Meyr991** [comment]
Just discovered another bug when I was testing it the last time…
`https://ewr1.vultrobjects.com/meyr/very%20much%20confused.png`
I don't think that's a golden retriever 😅
For some reason it switched the name of the files, and named that wrong
It's 5 AM, so I'll just mark the PR as ready, as it's not a breaking change, maybe we can fix it later :)
Maybe we could also provide an exe file? Probably would be easier, then having to setup python and install reqs
`https://ewr1.vultrobjects.com/meyr/tab_scraper.exe`
I created an exe from our code, if you like the idea, we can include it (Smart Screen will probably flag it, because the file doesn't have any certificates)

**Comment by Meyr991** [comment]
I did some testing before committing the code, but would be good if you did some too, maybe I missed something, cause I'm sleepy rn 🙃

**Comment by fruitTheory** [comment]
Yeah not in a rush or anything, but will add on discord just because. I think the exe is a great idea, not sure how to do that myself but will check the process.  Also read through everything and is looking good.

Would prefer to keep the multiple instances ability, check around fork line 137 vs main line 122  -- I think a good solution to keep both could be to do an if there is multiple instances runing use the if statement from main, else use the automatic while loop for one instance as default.

Also found two random/runny bugs in both scripts will put in issues tab(not anything that would prevent a merge)

Also just wondering what do you normally use for python UIs, just tkinker? I know lot of people use QT.. Also do you ever use c++?

**Comment by Meyr991** [comment]
For the exe, I just use a tool called auto-py-to-exe, which gives a GUI to pyinstaller, to create an exe.

I like the idea of integrating both, when I was testing, it was kind of annoying when it kept pulling me back to edge lol.

I normally just use tkinter yeah, if I need something more robust, I normally go with flutter.

I always try to stay away from c++ lol, but I assume it's also a great way of building desktop apps, but simple GUIs like this one idk, seems kind of overkill, same as flutter here, would be overkill.

Now, if you're thinking of integrating the scraper with the renamer or something like that, I think that going with one of those options would be a good idea, yeah.

**Comment by Meyr991** [comment]
Just to let you know, I'm not an experienced developer, so take this with a grain of salt.

**Comment by fruitTheory** [comment]
All good @Meyr991  was just curious -- but yeah I agree was going to say I view this as more of like a script tbh, and would not want to bother debugging it in C++ lol. I do want to start a long term C++ project for education purposes. But im so new in general I still can't quite read/follow most libraries.

**Pull request closed without merging**
